// Generated by CoffeeScript 1.3.3
var LocalNode;

LocalNode = (function() {

  function LocalNode(name, type) {
    this.name = name;
    this.type = type;
  }

  LocalNode.prototype.getInfo = function(prefix) {
    return console.log(prefix + " " + this.type + " | " + this.name);
  };

  LocalNode.prototype.validate = function() {
    return console.log('+++');
  };

  return LocalNode;

})();
