// Generated by CoffeeScript 1.3.3
var LocalNode;

LocalNode = (function() {

  function LocalNode(name, type, subtype) {
    this.name = name;
    this.type = type;
    this.subtype = subtype;
    this.parent = null;
    this.children = ['a'];
    this.scope = {};
    this.desc = "";
  }

  LocalNode.prototype.addChild = function(childNode) {
    this.children.push(childNode);
    return this.children;
  };

  LocalNode.prototype.addVariableToScope = function(variableName) {};

  LocalNode.prototype.searchForVariableInScope = function(variableName) {};

  LocalNode.prototype.print = function() {};

  LocalNode.prototype.validate = function() {
    return false;
  };

  return LocalNode;

})();
